[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
# Do not force this redirect for every request — allow Netlify to serve existing files
# (e.g. /assets/*) and only rewrite when a file is not found.